# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('description', models.TextField(default='description default text')),
                ('image', models.ImageField(height_field=225, upload_to=b'', width_field=225)),
                ('category', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
